alphagov/paas-docker-cloudfoundry-tools

.rspec
.travis.yml
Gemfile
Gemfile.lock
README.md
Rakefile
bosh-init/Dockerfile
spec/bosh-init/bosh-init_spec.rb
spec/spec_helper.rb

Story: https://www.pivotaltracker.com/n/projects/1275640/stories/109073500
* Rspec boiler plate for all containers
* Rspec tests for `bosh-init`
* Travis configuration
* Run docker locally
* Set docker environment variables if necessary. Example with docker-machine run:
```
eval "$(docker-machine env <machine>)"`
```
- `docker build -t bosh-init .`
- `bundle install`
- `rake`
- Fork repo
- Create PR
- Check for build result
Anyone but @saliceti or @combor

[#109073500] bosh-init testing

---

Rakefile

* Easier to maintain Rakefile
* Task to build bosh-init docker image
* `rake build:bosh_init`
* `rake spec`

[#109073500] Simple Rakefile

---

.travis.yml
README.md
Rakefile
spec/bosh-init/bosh-init_spec.rb
spec/spec_helper.rb
spec/spruce/spruce_spec.rb
spruce/Dockerfile
spruce/README.md

Build a container with spruce to be able to merge manifests on Concourse.
It uses a go alpine linux image as base to be able to compile go code while keeping a small image size.
* Run docker locally
* Set docker environment variables if necessary. Example with docker-machine run:
```
eval "$(docker-machine env <machine>)"`
```
* `bundle install`
* `rake build:spruce`
* `rake spec:spruce` will run the spruce test
* `rake` will run all the tests
* check the README for usage instructions
Anyone but @saliceti or @jimconner

[#109031802] spruce container

---

.travis.yml
README.md
Rakefile
mksecrets/Dockerfile
mksecrets/README.md
spec/curl-ssl/curl-ssl_spec.rb
spec/mksecrets/mksecrets_spec.rb
spec/spec_helper.rb

Container with utilities to generate secrets like passwords and possibly SSL and SSH keys in the future. This is required for generate-secrets tasks in concourse pipelines.
* Configure a local environment with docker and [serverspec](http://serverspec.org/)
* Build with `rake build:mksecrets`
* Test with `rake spec:mksecrets`
* Run commands like `docker run -i -t mksecrets pwgen` and
`docker run -i -t mksecrets sh -c "echo mysecret | mkpasswd -m sha-512"`
Anyone but me

[#110059806] Secrets generation

---

git-ssh/Dockerfile
git-ssh/git-ssh_spec.rb

[tag signing to control prod changes](https://www.pivotaltracker.com/story/show/115704725)
In order to do gpg tag verififcation we need the gnupg toolset to be installed
The PR has been written in the following context:
* I would like to
* Install gnupg in our docker contain so we can verify git tags that have been gpg signed.
* Download container and execute the gpg command
* Any man, woman or precocious child can review and merge this PR. If any members of the prestated group are unavailable I guess we can settle for a member of the core team instead. @actionjack and @HenryTK aren't allowed to merge this PR since they worked on it :-p

[#115704725]  tag signing to control prod changes

---

git-ssh/Dockerfile
git-ssh/git-ssh_spec.rb

what?
----
To initialise the concourse pool resource, we need to do some git commits.
For that We need to update the known_hosts file and configure git user and mail.
How to test?
-----------
```
rake build:git-ssh spec:git-ssh
```
And travis should pass
who?
----

[#115624569] Create the /root/.ssh directory and configure git email and user

---

terraform/Dockerfile
terraform/plugin_cache.tf
terraform/terraform_spec.rb

Upgrade Terraform to latest stable. See individual commits for more information.
1. Review the commits individually.
1. Test with other PRs on paas-cf, paas-bootstrap, and paas-release-ci.
Not @dcarley or @46bit

[#153119879] Upgrade Terraform to latest stable

---

bosh-cli-v2/Dockerfile
bosh-cli-v2/bosh-cli_spec.rb

Set the Subject Key Identifier when generating certificates
See https://github.com/alphagov/paas-bosh-cli/pull/1
Code review
❗️ The WIP commit needs to be updated with the final BOSH cli build
Not me.

[#157032509] Update BOSH cli to v3.0.1-gds1 (custom build)

---

bosh-shell/Dockerfile
bosh-shell/bosh-shell_spec.rb

What?
----
It is handy to have a good editor to be able to edit manifests.
How to review?
-----
Code review
Who?
---
not me

[#SUPPORT] Add vim to the bosh-shell container

---

cf-cli/Dockerfile
cf-cli/cf-cli_spec.rb
cf-uaac/Dockerfile

Increment the version of cf-cli in cf-cli docker image to allow use of `--assign-stack` argument.
* Code Review
* Test by building the image and using cf from it
Not me

Increment the version of CF_CLI

---

.travis.yml
self-update-pipelines/Dockerfile
self-update-pipelines/self-update-pipelines_spec.rb

- Uses @richardTowers Ruby pinning as that appears to be important
- Actually fixes broken test too (see commit message for what was going wrong)
- I've upgraded the awscli and changed the test as it was lacking loads of features but happy for that to be done separately if that is a contentious change
Closes #150
Closes #151

BAU: Fix broken Travis build

---

bosh-cli-v2/Dockerfile
bosh-cli-v2/bosh-cli_spec.rb
bosh-shell/Dockerfile
bosh-shell/bosh-shell_spec.rb
self-update-pipelines/self-update-pipelines_spec.rb

Co-authored-by: Mo <mohamed.deerow@digital.cabinet-office.gov.uk>
Co-authored-by: Toby <toby.lornewelch-richards@digital.cabinet-office.gov.uk>

Add credhub to bosh-shell and bosh-cli-v2

---

bosh-shell/startup.sh

What
---
Silences the SSH tunnel output so that the container output is friendlier to scripts
How to review
---
1. Code review
Who can revew
---
Not me

[#167971884] Silence the SSH tunnel output to make the container output friendlier to scripts

---

terraform/Dockerfile
terraform/plugin_cache.tf
terraform/terraform_spec.rb

We're updating terraform so we need to update the container that will be performing the deployment on concourse
Code review and check the tests pass
@AP-Hunt

Update terraform version to 0.12.29 and update plugins

---

cf-cli/Dockerfile
cf-cli/cf-cli_spec.rb

So we can interact with the autoscaler in our pipelines

cf-cli: install app autoscaler plugin

---

certstrap/certstrap_spec.rb
terraform/Dockerfile
terraform/plugin_cache.tf
terraform/terraform_spec.rb

We're updating terraform so we need to update the container that will be performing the deployment on concourse
Code review and check the tests pass
@paroxp

Update terraform to 0.13.2

---

cf-cli/Dockerfile
cf-cli/cf-cli_spec.rb

Hi There!
A PR to bump to latest cli available (cf and spruce)

cf-cli: update to v7.2.0; spruce to v1.27.0

---

terraform/Dockerfile
terraform/terraform_spec.rb

Terraform 0.14 is out, so we should start upgrading

Update terraform to last version in the 0.13 series

---

terraform/Dockerfile
terraform/terraform.lock.hcl
terraform/terraform_spec.rb

It's time to upgrade so let's get the containers ready

Update terraform to version 0.14.4

---

golang/Dockerfile

Update the docker version to 1.16

Update docker version

---

.github/workflows/image_alpine.yml
.github/workflows/image_awscli.yml
.github/workflows/image_curl-ssl.yml
.github/workflows/image_git-ssh.yml
.github/workflows/image_golang.yml
.github/workflows/image_json-minify.yml
.github/workflows/image_middleman.yml
.github/workflows/image_node-chromium.yml
.github/workflows/image_node.yml
.github/workflows/image_paas-prometheus-exporter.yml
.github/workflows/image_psql.yml
.github/workflows/image_ruby-base.yml
.github/workflows/image_ruby.yml
alpine/Dockerfile
node/Dockerfile
ruby-base/Dockerfile
ruby-base/README.md

Upgrade alpine to 3.16 across containers which use it as a base image.
* Code review
* Check tests have run
* This should be merged before #236 
* the "REMOVE_ME_PRE_MERGE" commit needs to be dropped before merging
* Move on to #237

[#182295946] Upgrade alpine to 3.16

---

certstrap/Dockerfile
cf-acceptance-tests/Dockerfile

use our ubuntu base for certstrap + cf-acceptance-tests
Must wait for #249 to complete, then rerun workflows and ensure they pass

Dogfood our ubuntu image

---

.github/workflows/build-image-base.yml
git-ssh/Dockerfile
terraform/Dockerfile
terraform/terraform_spec.rb

Updates 
- terraform to 1.3.3
- build-push-action to 3.2.0
- git in dockerfile to 2.36.3-r0
Check that the changes make sense and all the tests pass

Upgrade terraform to 1.3.3

---

cf-uaac/Dockerfile
cf-uaac/cf-uaac_spec.rb

cf-uaac < 4.0 does not support Ruby < 3.0
Tests pass?

[#183708862] Upgrade to cf-uaac 4.7.0

---

.github/workflows/image_kipper.yml
kipper/Dockerfile
kipper/README.md

added new docker image for Kipper with bosh and awscli for running Kipper startup/shutdown script from a single task in pipelines.
Read the code

added new docker image for Kipper with bosh and awscli

---

kipper/Dockerfile

added curl and updated awscli version for kipper
look at the code

added curl and updated awscli version to get taglist metadata for kipper

---

.github/workflows/image_keyval-resource.yml
keyval-resource/Dockerfile
keyval-resource/README.md

Adding keyval-resource for concourse
Look at the changes

add keyval resource for concourse

---

.github/workflows/image_concourse-keyval-resource.yml
concourse-keyval-resource/Dockerfile
concourse-keyval-resource/README.md
curl-ssl/Dockerfile
git-ssh/Dockerfile

Added concourse-keyval-resource to make build metadata available for dev-env-usage
Look at the code

added concourse keyval resource for dev-env-usage

---

node/Dockerfile

Upgrade nodeJS docker image to node:lts-alpine3.18 which contains node 20 that CI needs to build paas-admin on
not sure how you test this

Update nodeJS docker image

---

concourse-pool-resource/Dockerfile

bumped concourse-pool-resource version to 1.4.0
look at the code

bumped concourse-pool-resource version to 1.4.0
