alphagov/paas-docker-cloudfoundry-tools

spec/spruce/spruce_spec.rb, spruce/Dockerfile
[#109060102 Implement logic to pin the spruce version](https://www.pivotaltracker.com/story/show/109060102)
What
----
We need to pin the version of the spruce command, to avoid uncontrollerd
upgrades of the spruce binary with any upstream changes.
For that we use git tags to implement version pinning for the spruce command.
We cannot use [release binaries](https://github.com/alphagov/paas-docker-cloudfoundry-tools/tree/spruce_from_release)
because they are dynamically compiled and they fail on alpine, so we get
the spruce code, checkout the version tag
and rebuild the binary.
How to test?
------------
(Note: recommended use a ruby manager like RVM)
```
bundle install
bundle exec rake build:spruce spec:spruce
```
Who?
----
=> [#109060102] Implement logic to pin the spruce version

.travis.yml, README.md, Rakefile, curl-ssl/Dockerfile, curl-ssl/README.md, spec/curl-ssl/curl-ssl_spec.rb, spec/spec_helper.rb
[#109060102 Add new container curl-ssl](https://www.pivotaltracker.com/story/show/109060102)
Implement a new container curl-ssl which includes the curl command with SSL support and openssl binary.
The container is based on Alpine:3.3
The spec check won't use the serverspec package resource because it does
not support alpine. Instead, we use the `apk` command directly.
This PR depends on #8 being merged first, to pin the spruce version (merged already)
Using the rake file (I recommend use of [RVM](http://getrvm.io)):
```
bundle install
bundle exec rake build:curl_ssl spec:curl_ssl
```
You can also test the commands:
```
docker run -i -t curl-ssl curl https://www.google.com
docker run -i -t curl-ssl openssl
```
=> [#109060102] Add new container curl-ssl

spec/bosh-init/bosh-init_spec.rb, spec/curl-ssl/curl-ssl_spec.rb, spec/spec_helper.rb, spec/spruce/spruce_spec.rb
It momentarily confused me why the tests wouldn't work locally. I've removed
the `should be available` test because this doesn't report the correct thing
when `@image` is `nil`. Because of this we no longer need `@image`, we just
want the ID.
Before:
1) bosh-init image should be available
Failure/Error: set :docker_image, @image.id
NoMethodError:
undefined method `id' for nil:NilClass
After:
1) bosh-init image installs the right version of Ubuntu
Failure/Error: raise "Docker image '#{name}' not found. You may need to run 'rake build:<name>' first" unless image
RuntimeError:
Docker image 'bosh-init:latest' not found. You may need to run 'rake build:<name>' first
=> Improve error message when tests can't find image

spec/spec_helper.rb
This reverts commit cdd1579b9af644b669285bd2e987207b01abb730.
This was intended to work with a remotely pulled image as well as the more
common use case of a locally built image. However if a remote image has been
pulled then the local image will never be used:
➜  paas-docker-cloudfoundry-tools git:(master) docker tag -f ubuntu:14.04 spruce
➜  paas-docker-cloudfoundry-tools git:(master) docker images | grep spruce
spruce                   latest              89d5d8e8bafb        4 weeks ago         187.9 MB
governmentpaas/spruce    latest              9ca91d2c99ff        4 weeks ago         275.3 MB
➜  paas-docker-cloudfoundry-tools git:(master) b irb
irb(main):001:0> require 'docker'
=> true
irb(main):002:0> Docker::Image.all().detect{|i| i.info['RepoTags'][0].end_with? 'spruce:latest' …
=> Revert "Find images by suffix rather than exact match"

bosh-init/Dockerfile, bosh-init/README.md, bosh-init/bosh_init_cache/minimal-state.json, bosh-init/bosh_init_cache/minimal_in.yml, bosh-init/bosh_init_cache/seed_bosh_init_cache.sh, spec/bosh-init/bosh-init_spec.rb
Every time bosh-init runs in concourse it has to compile the CPI, which takes 3-5 minutes
This adds a step to the build for the bosh-init container to run a dummy deploy which in turn causes the CPI to be compiled and cached in `/root/.bosh_init`.
The cached CPI version has to match the version being used in the manifests used by bosh-init for the cache to be used.
Secondly, the compilation cache is keyed from the `installation_id` which is written to the bosh state.json file. bosh-init generates a random id for new deployments that don't yet have a state file. To work around this, this creates a state.json file containing a predefined installation_id before running bosh-init.  To use the cached version it's then necessary for all runs of bosh-init to use this same `installation_id` (see …
=> [#111137450] Cache bosh-init AWS CPI compilation in image

.travis.yml, Rakefile, awscli/Dockerfile, awscli/README.md, spec/awscli/awscli_spec.rb, spec/spec_helper.rb
[#108441228 Automatically shutdown dev environments at night / weekends](https://www.pivotaltracker.com/story/show/108441228)
What
----
We want to be able to stop the vagrant AWS vm at nights. We will use AWS
cli tools to send the command to terminate it.
Scope
-----
Add a container including the AWS client tools. We create it based on
the curl container, so that we can use curl for querying the metadata.
How to test this?
-----------------
Run the tests:
```
bundle install # I recommend rvm
rake build:awscli spec:awscli
```
Run the container:
```
docker run awscli aws --version
```
Who?
----
Anyone but @keymon or @actionjack
=> [#108441228] Add container for AWS cli tool

certstrap/Dockerfile, certstrap/README.md, certstrap/certstrap_spec.rb
[Auto-generate SSLs for all internal components](https://www.pivotaltracker.com/story/show/111428758)
What
----
We want to generate the certificates for all the components, signed by a CA which is trusted by all the related VMs.
For that, we will use [certstrap](https://github.com/square/certstrap/) tooling to simplify management of the certificates.
In the concourse job pipelines we will also interact with S3 using the script `s3init.sh`, so we must include `curl` and `ca-certificates`.
how to test:
-----------
Travis tests should execute the spec added in this PR and pass .
```
rake build:certstrap spec:certstrap
```
Notes
-----
A docker hub automated build must be setup with this Dockerfile.
The PR https://github.com/alphagov/paas-cf/pull/92 must be updated to use
the new container …
=> [#111428758] Add a container certstrap CA manager tool

cf-cli/Dockerfile, cf-cli/README.md, cf-cli/cf-cli_spec.rb, curl-ssl/README.md
This contains the CF CLI, and a Go runtime. This will be used to run the
acceptance tests in concourse.
=> [#112503901] Create cf-cli image

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/README.md, cf-acceptance-tests/cf-acceptance-tests_spec.rb
So that we can fetch the dependencies at runtime instead of vendoring them.
=> [#112503901] Add godep to cf-acceptance-tests container

bosh-cli/Dockerfile, bosh-cli/README.md, bosh-cli/bosh-cli_spec.rb
#What 
The bosh-resource container lacks the SSH binary, meaning that the 'bosh ssh' command does not work. This PR adds a new container for bosh-cli which has both BOSH and SSH commands installed.
Follow the instructions in the README.md
Anyone except @alext or myself.
=> [#112908839] Workflow for Bosh SSH

bosh-init/Dockerfile
In this PR we are raising the version of bosh_aws_cpi that includes a fix for max retries for calls to AWS. 
bosh-aws-cpi-release v 44 exposes AWS SDK retry option (max_retries) with default of 2
Reference [Changelog](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/releases/tag/v44)
This PR should be merged before https://github.com/alphagov/paas-cf/pull/107
Use bosh-init container do deploy microbosh and check whether you are getting any 'Rate limit exceeded' errors. You need to modify concourse/pipelines/create-microbosh.yml and add #112411703-bump-bosh-aws-cpi-release tag to the bosh-init contaier. For instance:
```image: docker:///governmentpaas/bosh-init#112411703-bump-bosh-aws-cpi-release```
Anyone but @actionjack or @combor
=> Bump bosh-aws-cpi release to 44.

bosh-cli/Dockerfile, bosh-cli/bosh-cli_spec.rb
httpclient (which is a dependency of bosh-cli) has a [check for the
openssl version](https://github.com/nahi/httpclient/blob/v2.7.1/lib/httpclient/ssl_config.rb#L441-L452) to ensure it includes fixes for a vulnerability.
Versions below this cause it to emit warnings.
Because debian backports security fixes instead of upgrading openssl,
these warnings are triggered here, even though openssl is no longer
vulnerable.
Digging further, the CVE mentioned in the comment in httpclient
specifies that the only versions affected are 1.0.1n, 1.0.1o, 1.0.2b and
1.0.2c, so the httpclient check identifies non-vulnerable versions as
vulnerable.
To work around this, we've switched the bosh-cli container to be based
on alpine, which includes the newer versions of openssl.
=> [#112908839] Update bosh-cli openssl version.

bosh-cli/Dockerfile, bosh-cli/bosh-cli_spec.rb
Without this, we are seeing warnings from `bosh upload relase` saying
"sh: file: not found". Despite this, the bosh upload seems to still
work.
Given this is evidently a dependency of the bosh-cli it seems better
that we include it.
Came across this while looking at making the release upload process
deal with more than one version of a release.
=> [#110652158] Add `file` utility to bosh-cli container.

terraform/Dockerfile, terraform/README.md, terraform/terraform_spec.rb
What
----
We want to be able to create roles and DBs in postgres using terraform to create
the DBs for the RDS based CF databases.
As we add this change, we will import the separated repository
in https://github.com/alphagov/paas-docker-terraform to
this repository, as this is where we are implementing all the containers.
Context
-------
* I want to import the code and history from https://github.com/alphagov/paas-docker-terraform
* and include the postgres provider
How to test?
------------
As usual in this repo, by travis or:
```
rvm use --create 2.2.2@containers
bundle install
bundle exec rake
```
Who?
----
=> [#114193485] Add terraform container from other old repository and enable postgresql

terraform/Dockerfile, terraform/terraform_spec.rb
There's an issue with earlier versions when handling a security group
with multiple ingress blocks for the same port range. It results in
terraform updating the resource on every run. This is no longer the case
with 0.6.12. See https://github.com/hashicorp/terraform/issues/5301#issuecomment-188746760 for details of this issue.
See also the related paas-cf PR - https://github.com/alphagov/paas-cf/pull/123
This is best reviewed in conjunction with the above paas-cf PR. See notes there for details.
Anyone but mysql.
=> [#113824903] Bump terraform to 0.6.12

psql/Dockerfile, psql/README.md, psql/psql_spec.rb
Create psql Postgres client container so we can run psql commands from Concourse. This is necessary to set up the CF RDS database.
Contains test and README.
* build: `rake build:psql`
* test: `rake spec:psql`
* run: `docker run psql psql --version`
Anyone but @mtekel or me
=> [#114193485] Create psql docker container

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
[#114186797 Run smoke tests and acceptance tests in concourse task rather than errand](https://www.pivotaltracker.com/story/show/114186797)
What
----
We want to run the cf-acceptance-tests on concourse directly, but as they
[call unzip command](https://github.com/cloudfoundry/cf-acceptance-tests/blob/e5e7b4726f61f9e66da43c1daf0151d6b4492be1/v3/package_test.go#L75),
we need to install the package in the container.
How to test this
----------------
As usual, follow README instructions and:
```
rake build:cf-acceptance-tests spec:cf-acceptance-tests
```
Travis tests should be OK.
Who?
----
=> [#114186797] Add unzip command to cf-acceptance-tests container

spruce/Dockerfile
Story: [Fix the paas-docker-cloudfoundry-tools build](https://www.pivotaltracker.com/story/show/115258555)
It looks like the spruce tag we are pinning to in the Docker file
was modified as it doesn't compile because of a failed dependency.
As the dependencies are vendored, a simple fix is to add the spruce
repository to $GOPATH.
* Load the ruby environment related to the Gemfile
* `rake build:spruce`
* `rake spec:spruce`
* run:
```
$ docker run spruce spruce --version
spruce - Version 0.13.0 (master)
```
Anyone but @keymon or me
=> [#115258555] Fix spruce container 0.13.0

cf-cli/Dockerfile, cf-cli/README.md, cf-cli/cf-acceptance-tests_spec.rb
[#113749465 Make Cloud Foundry Metrics Available](https://www.pivotaltracker.com/story/show/113749465)
What?
-----
We need a container to be able to deploy CF apps in a task. We also need some other tools
like curl, unzip and git to be able to download, uncompress or clone/checkout dependencies.
Container with CF client command and some other tools to help deploying
apps in cloudfoundry: curl, git, unzip.
Based on Debian wheezy, as the distributed binary cf-cli depends on the
libc of a Debian like linux distro (alpine won't work).
Dependencies
-------------------
This is required before https://github.com/alphagov/paas-cf/pull/139 is merged.
Test
----
Travis should run the tests and end successfull.
To run tests locally: `rake build:cf-cli spec:cf-cli`
Who?
----
=> [#113749465] Add container with cf-cli andd tools for deploy

self-update-pipelines/Dockerfile, self-update-pipelines/README.md, self-update-pipelines/self-update-pipelines_spec.rb
[#114000923 self-updating pipelines](https://www.pivotaltracker.com/story/show/114000923)
What
----
We want to be able to update concourse pipelines from concourse itself, using
the same scripts that we use to setup the pipelines.
Add a self-update-pipelines container to run jobs which update the pipelines
in concourse using the configuration scripts.
These scripts require bash, curl, ruby and make.
How to test
-----------
As usual: `make build:self-update-pipelines spec:self-update-pipelines` and
travis should success.
Who?
----
=> [#114000923] Add self-update-pipelines container to run update pipelines related scripts

.travis.yml, Rakefile
This will give us early feedback on build errors, and make it more obvious what has actually errored.
At present, if a build fails, the rake task doesn't exit non-zero, so everything else continues, and then the tests fail, and it's not easy to see what the actual problem is.
Cause one of the image builds to fail (eg by adding a `RUN false` line to the `Dockerfile`). Then run `bundle exec rake build:all`, and verify that it exits non-zero immediately that it encounters the error.
Anyone but myself.
=> Make build rake tasks exit non-zero on error

git-ssh/Dockerfile, git-ssh/README.md, git-ssh/git-ssh_spec.rb
Story: [Create tags for deploying to staging and prod](https://www.pivotaltracker.com/story/show/115318605)
We need to push to Git using SSH. We avoid the Git resource because we would have to expose the private key. This container is required to run Git within a task.
* Build: `rake build:git-ssh`
* Test: `rake spec:git-ssh`
* Play:
```
docker run git-ssh git --version
docker run git-ssh ssh -V
```
Anyone but @mtekel or myself
=> [#115318605] Add Git container with SSH support

git-ssh/Dockerfile, git-ssh/git-ssh_spec.rb, terraform/Dockerfile, terraform/terraform_spec.rb
This was created to investigate issue [AWS: Can't update certificate associated with ELB](https://github.com/hashicorp/terraform/issues/5713) in story [ELB for access to logs](https://www.pivotaltracker.com/story/show/115320097).
This has not fixed that particular issue, but the whole pipeline was tested on that terraform version and it worked fine.
There is a also a minor improvement as the Alpine version is now pinned to 3.3.
Use `image: docker:///governmentpaas/terraform#115320097-terraform-0.6.13` in the pipeline and deploy.
Anyone but @HenryTK or myself
=> [#115320097] Terraform 0.6.13

terraform/Dockerfile, terraform/terraform_spec.rb
[#115624569 Implement locking for pipelines](https://www.pivotaltracker.com/story/show/115624569)
We need to start using the resource `aws_iam_user_ssh_key` to be able to upload ssh keys to users to access codecommit.
Until there is not a new release of terraform, we will build it from source
```
rake build:terraform spec:terraform
```
and travis should pass. Try building your environment using this new image. To do that, update links in the pipeline like this :
```
-        image: docker:///governmentpaas/terraform
+        image: docker:///governmentpaas/terraform#new-tf-build
```
Anyone but @keymon or @mtekel
=> [#115624569] Build terraform from master git repo

self-update-pipelines/Dockerfile, self-update-pipelines/self-update-pipelines_spec.rb
[#115624569 Implement locking for pipelines](https://www.pivotaltracker.com/story/show/115624569)
What?
---
For the setup of the pool resource for the pipeline locking, we need
to download some objects from S3. We decided use aws cli for this.
Context?
------
In this commit we install awscli from pip in ubuntu.
Test this?
-------
check #14 and #35
Who?
---
=> [#115624569] Instal awscli in self-update-pipelines container

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
Current [vegeta](github.com/tsenart/vegeta) code has been moved to Go 1.6 and fails with earlier Go versions with:
```
github.com/tsenart/vegeta/lib/attack.go:156: tr.TLSNextProto undefined (type *http.Transport has no field or method TLSNextProto)
```
We need to bump GO version to 1.6
run:
```
docker build -t cf-acceptance-tests .
docker run cf-acceptance-tests go version
``` 
and check if go version is 1.6
Not @keymon or @combor
=> [#117021589]  Go version bump to 1.6

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb, cf-cli/Dockerfile, cf-cli/cf-acceptance-tests_spec.rb
The cf-acceptance-tests include a check that the cf command line client meets the required version.
For CF v233 the required version for the cli is 6.16.1
This PR bumps the version numbers in the Dockerfile and spec file.
```
docker rmi cf-cli # Remove any existing image for cf-cli on your machine
docker build -t cf-cli .
docker run -i -t cf-cli cf --version
```
Repeat the above steps for the cf-acceptance-test container too as this PR updates both containers.
Anyone on the team except for @HenryTK or myself.
=> [#116983391] Bump cf-cli versions to meet reqs for CF v233

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb, cf-cli/Dockerfile, cf-cli/cf-acceptance-tests_spec.rb
Reverts alphagov/paas-docker-cloudfoundry-tools#45, as it seems to make acceptance tests fail
=> Revert "[#116983391] Bump cf-cli versions to meet reqs for CF v233"

git-ssh/Dockerfile, git-ssh/git-ssh_spec.rb
What
----
We use fair complex scripts with this containers, on which we want
to set options like pipefail [1]. Alpine `sh` does support that option
but not the GNU sh, which causes the scripts fail if they are
executed or tested outside of this container (e.g. travis).
To solve this, we install bash in the container so that we can use
it in the scripts and make them portable.
How to test
---------
just run `rake build:git-ssh spec:git-ssh`. Travis should succed
Who?
---
Anyone but @keymon or @henrytk
[1] https://bclary.com/blog/2006/07/20/pipefail-testing-pipeline-exit-codes/
=> [#117522857] Install bash in the git-ssh container

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb, cf-cli/Dockerfile, cf-cli/cf-acceptance-tests_spec.rb
Sometimes there is this amazing feeling of deja-vu.... This PR reverts the reversion of the earlier commit to use cf cli 6.16.1 16dc7b45179895dde86a8ac4bb466cf3d74495aa.
The cf-acceptance-tests include a check that the cf command line client meets the required version.
For CF v233 the required version for the cli is 6.16.1
This PR bumps the version numbers in the Dockerfile and spec file.
```
docker rmi cf-cli # Remove any existing image for cf-cli on your machine
docker build -t cf-cli .
docker run -i -t cf-cli cf --version
```
Repeat the above steps for the cf-acceptance-test container too as this PR updates both containers.
Anyone on the team except for @saliceti, @HenryTK or myself.
=> Re-enable cf cli version 6.16.1 again

cf-uaac/Dockerfile, cf-uaac/README.md, cf-uaac/cf-uaac_spec.rb
##What
In order to create temporary admin accounts for use in the acceptance-tests and smoke-test steps in our pipeline, we need to use the CF `uaac` command line client. This means that we're going to need a docker image with the `uaac` command available.
This container will use uaac version 3.2.0, which will work with our current CF v233 release.
Build the container using `rake build:cf-uaac`
Check that it passes it's rspec tests using `rspec cf-uaac/cf-uaac_spec.rb` 
Get a shell running in the conainer using `docker run -i -t cf-uaac ash`
Run the `uaac` command and confirm that it returns it's help page.
Not @mtekel or myself
=> [#117705909] Add cf-uaac container

cf-acceptance-tests/README.md
The README was wrong when it comes to Go complier version.
Check it the version in Dockerfile and Readme are same.
Not me
=> We use Go 1.6 not 1.5

cf-cli/Dockerfile, cf-cli/cf-acceptance-tests_spec.rb
This adds ruby to the cf-cli container so that we can script operations against the CF API more easily (eg
adding the security groups defined in the manifest).
Verify that the tests pass. Verify that the cf-cli container does indeed have ruby available.
Anyone but myself.
=> [#117512371] Add ruby to cf-cli container.

bosh-init/Dockerfile, bosh-init/bosh-init_spec.rb, bosh-init/bosh_init_cache/seed_bosh_init_cache.sh
As part of the RDS broker story, we needed to upgrade the AWS CPI to get the change to allow security groups to be defined in a resource pool (https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/pull/28).
This PR therefore updates the cached CPI compilation to match the version used in the pipelines.
🚨  This should be merged along with https://github.com/alphagov/paas-cf/pull/260
Code review.  Build container, and verify that tests pass.
Anyone but myself, @timmow or @jimconner
=> [#117512371] Upgrade the cached bosh-aws-cpi to version 52

bosh-cli/Dockerfile, bosh-cli/bosh-cli_spec.rb
bosh_cli gem version is now pinned in paas-cf. We want to use the same
version in the container as well.
* Build and run local tests
* Run the bosh-cf pipeline with the new container by replacing `docker:///governmentpaas/bosh-cli` with `docker:///governmentpaas/bosh-cli#update_bosh_cli_gem`
Anyone but me
=> [#118838943] Update bosh_cli gem to 1.3232.0

awscli/Dockerfile, awscli/awscli_spec.rb
In order to add aws sts `get-caller-identity` command which we need for
tagging RDS instances in upgrade master password story (#118841005).
Run `rake build:awscli`. Then `rspec awscli`. You can check that the version inside container matches by hand and you can also check that it has `aws sts get-caller-identity` command.
not me
=> Bump AWS CLI version to 1.10.38

spruce/Dockerfile, spruce/README.md, spruce/spruce_spec.rb
Spruce now provides static builds, which enables us to run it from
Alpine (see https://github.com/geofffranks/spruce/issues/128).
Use new spruce binary to reduce container size by 80%:
* old 73MB
* new 14MB
Render manifests using old spruce. Render manifest using new spruce. Compare - there should be no differences. You could also upgrade your local spruce to 1.4.5 & run manifest rendering tests (or all tests - `make test`)
You can also render locally and compare outputs with previous spruce version:
```
cd manifests
shared/build_manifest.sh cf-manifest/manifest/*.yml cf-manifest/manifest/data/*.yml cf-manifest/manifest/env-specific/cf-default.yml cf-manifest/manifest/runtime/runtime.yml shared/spec/fixtures/*.yml shared/spec/fixtures/terraform/terraform-outputs.yml >manifest.yml
```
not …
=> [#111700216] Upgrade spruce to 1.5

bosh-cli/bosh-cli_spec.rb, json-minify/Dockerfile, json-minify/README.md, json-minify/json-minify_spec.rb
[#122183539 - Visibility of important platform metrics](https://www.pivotaltracker.com/story/show/122183539)
We require use of the json-minify Ruby Gem to insert JSON as values in our CloudFoundry manifest. Each of these lines represents the configuration of a Grafana dashboard. This image allows us to isolate this dependency and not have to run bundler in the pipeline.
* Check out the `122183539_json_minify` branch
* Run the following to verify the `json-minify` Gem is installed:
```
cd json-minify
docker build -t json-minify .
docker run json-minify gem list
```
* Run `rspec json-minify/` to ensure the test passes.
Anyone but @saliceti or me
=> [#122183539] Add json-minify container

bosh-cli/Dockerfile, bosh-cli/bosh-cli_spec.rb
The current version of the ruby:2.2-alpine no longer includes the
openssl CLI. That means that the busybox provided wget command can no
longer connect to https sites, and instead gives the following error:
```
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
```
This adds openssl to this container to fix this issue.
This is a partial revert of cfc7785e, which updated the tests to check for
the libssl version instead because we didn't think that the openssl CLI
was needed.
Verify that the tests pass in Travis.
Verify that wget works with https sites:
```sh
cd bosh-cli
docker rmi ruby:2.2-alpine # To ensure we get the latest.
docker build -t bosh-cli .
docker run bosh-cli wget https://www.google.com
```
Anyone but myself.
=> [#122183539] Fix wget in bosh-cli container for https sites.

bosh-init/Dockerfile, bosh-init/bosh-init_spec.rb
Upgrade bosh-init version. This is required to deploy new concourse version, which uses various
"BOSH 2.0" features that are not supported in our previous bosh-init version.
As a part of https://github.com/alphagov/paas-cf/pull/381
not @mtekel or @combor
=> [#117991263] Upgrade bosh-init to 0.0.95

.travis.yml, Gemfile, Gemfile.lock
[#126965751 Test users not removed from CC DB.](https://www.pivotaltracker.com/story/show/126965751)
What
====
Pin ruby version in travis to ruby 2.2, as  we are having issues building json gem in travis ([here](https://travis-ci.org/alphagov/paas-docker-cloudfoundry-tools/builds/147760906#L165) vs [here](https://travis-ci.org/alphagov/paas-docker-cloudfoundry-tools/builds/152935537#L301)) and we decided to use ruby 2.2 as the standard in the team.
Additionally Travis docker service has been upgraded and we need to upgrade the clients. Otherwise, the builds fail [with this error](https://travis-ci.org/alphagov/paas-docker-cloudfoundry-tools/builds/153019275#L1860):
``` 
Failure/Error: image = Docker::Image.all().detect{ |i| i.info['RepoTags'].include? name }
Docker::Error::ClientError: …
```
=> [#126965751]  Upgrade to docker-api 1.31 gem and pin ruby to 2.2 to support travis

psql/Dockerfile, psql/psql_spec.rb
Alpine remove old versions of the postgres client from their `main` apt
index when upgrading, meaning this will frequently break. The postgres
client libraries are backward compatible so there's no need to pin.
=>  [#126965751] Unpin the postgresql client version

cf-cli/Dockerfile, cf-cli/cf-acceptance-tests_spec.rb
[#126965751 Test users not removed from CC DB](https://www.pivotaltracker.com/story/show/126965751)
What
====
We need to parse the output of `cf curl /v2/users` to list all the existing users created by the acceptance tests. For this jq is perfect.
We consider that this really useful and it will be used in other stories in the future, so we add it as a basic tool in the cf-cli container.
We want to use the regex based functions, so jq must be >= 1.5 and must be compiled with ONIGURUMA regex library. The Ubuntu package is 1.4, so we will pull the static binary released upstream.
Dependencies
-----------------
Please merge #65 first and rebase.
This could be reviewed together with https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/62
How to test?
-----------
Travis shall pass. …
=> [#126965751] Add jq 1.5 to the cf-cli container

cf-cli/Dockerfile, cf-cli/cf-acceptance-tests_spec.rb
[#126965751 Test users not removed from CC DB.](https://www.pivotaltracker.com/story/show/126965751)
What
====
We use alpine base image whenever is possible to speed up the pipelines.   But in the case of cf-cli we were using Ubuntu because [the cf-cli was not compiled statically](https://github.com/cloudfoundry/cli/issues/807). Since 6.17.1. they build it statically, so we can move the container to alpine.
Dependencies
------------
Please merge #65, and #61 first and rebase
How to test
-----------
Travis shall pass.
You can test locally with `rake build:cf-cli spec:cf-cli`.
Then you can test: `docker run -ti cf-cli jq --version`
Who?
----
Anyone but @richardc or @keymon
=> [#126965751] Use Alpine for cf-cli container base image

cf-cli/Dockerfile, cf-cli/cf-acceptance-tests_spec.rb
[#126965751 Test users not removed from CC DB.](https://www.pivotaltracker.com/story/show/126965751)
What
====
After merging #62, our pipeline fail when executing a ruby script which required json.                                                            
Although json is one of the basic packages shipped with ruby[1], Alpine extracts it in a different package ruby-json. We need to explicitely add that dependency.                                                
We avoid running `bundle install` in the pipeline to avoid increase the time to run. We normally try to keep the scripts simple and without dependencies, but `json` is a really basic library.                 
[1] https://zzz.buzz/2016/02/29/default-gems-bundled-with-ruby/                 
[2] …
=> [#126965751] Install ruby gem json in cf-cli container

terraform/README.md
This no longer applies since we've upgraded to 0.7 (in fa630ad) as
terraform now has a single binary that includes all the built-in
providers.
Review update README and confirm it makes sense to remove these details.
Anyone but myself.
=> [#130003999] Remove container size info from terraform README.

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
Adding the Ginkgo binary will allow us to parallelise our custom acceptance tests. This will make testing the RDS broker much quicker, as the tests will now create several database instances as part of the changes in story #127970229[1]
[1] https://www.pivotaltracker.com/story/show/127970229
* Pull this branch and `cd` into the `cf-acceptance-tests` directory. Run `rake build:cf-acceptance-tests && rake spec:cf-acceptance-tests`
* Change every pipeline task that uses the image to pin this version (add `image_resource.source.tag: 127970229_final_snapshot`) and run the pipeline.
* or as a part of https://github.com/alphagov/paas-cf/pull/508 which has a TMP commit to do the above
Anyone but me or @mtekel
=> [#127970229] Add Ginkgo to cf-acceptance-tests image

terraform/Dockerfile, terraform/terraform_spec.rb
We have modified both, `terraform` and the `go-datadog-api` packages,
enabling simple addition of two desired keys `style` and `type` to
the graph implementation for each dashboard.
This has been planned out, as part of the
[#131428567 - Add options to datadog terraform provider][1].
This should allow us, to continue with the
[#120590777 - Improve Visibility of Continuous Smoke Tests][2] story.
The [*TEMP* branch on `paas-cf`][3] has been created for the first two points.
Not @saliceti or @paroxp
[1]: https://www.pivotaltracker.com/story/show/131428567
[2]: https://www.pivotaltracker.com/story/show/120590777
[3]: https://github.com/alphagov/paas-cf/tree/131428567_terraform_update
[l117]: https://github.com/alphagov/paas-cf/blob/a13ada57d30016dd083d04594c7f3c633a441ff5/concourse/pipelines/c …
=> [#131428567] Apply custom terraform build

bosh-cli/Dockerfile, bosh-cli/bosh-cli_spec.rb
[#132060265 Support: Wrong version of aws-broker deployed in CI](https://www.pivotaltracker.com/story/show/132060265)
What?
-----
We want to add a check to verify that the tag of the cloned version of  a bosh release matches with the intended version to upload before uploading it.
For that, we need git in this image to check tags or gather any git information from the git repositories of the bosh releases that we build.
How to review?
--------------
Travis should pass. You can run `rake build:bosh-cli spec:bosh-cli`
You can review it with the corresponding PR in paas-cf.
Who?
----
=> [#132060265] Add git to bosh-cli image

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
CF 245 requires a newer CLI version than the one in this container (6.16.1). This PR therefore upgrades this to 6.21.1, which is also the version that the `cf-cli` container is already using (it was upgraded in a2d25c4).
To test locally:
`bundle exec rake build:cf-acceptance-tests spec:cf-acceptance-tests`
`docker run --rm cf-acceptance-tests cf -v` should return version 6.21.1
Anyone but @keymon or myself.
=> [#132651425] Upgrade cf-cli in cf-acceptance-tests to 6.21.1

bosh-init/Dockerfile
[#132681767 Upgrade BOSH #2: stemcell, CPI and new features](https://www.pivotaltracker.com/story/show/132681767)
What
----
We upgraded the CPI in bosh in PR https://github.com/alphagov/paas-cf/pull/570
We upgrade the cached CPI in the bosh-init to bring it inline with the version used in our pipelines.
Dependencies
------------
This should be merged together with PR https://github.com/alphagov/paas-cf/pull/570
How to test?
-----------
Travis tests this, should pass.
Otherwise: `rake build:bosh-cli spec:bosh-cli`
Who?
----
=> [#132681767] Upgrade the cached bosh-aws-cpi to version 60

Gemfile, Gemfile.lock, terraform/Dockerfile, terraform/terraform_spec.rb
[#133751193 Enable datadog BOSH healthmonitor integration](https://www.pivotaltracker.com/story/show/133751193)
What?
-----
We want to upgrade terraform to use a patched version of the datadog provider.
Latest version is 0.7.10. There is no need to use our forked version of terraform anymore, so we go back to the code that downloads the official binary.
We were forced to upgrade the gem for docker-api for our tests, as the docker API has changed and the tests fail in the latest docker versions (~>1.12)
How to test?
-----------
Check Travis should pass.
You can optionally run `rake build:terraform spec:terraform`.
Who?
----
Anyone but @keymon or @saliceti
=> [#133751193] Upgrade terraform container to 0.7.10

bosh-cli/Dockerfile, bosh-cli/bosh-cli_spec.rb
In order to build boshreleases that contain packages with pre_packagging steps, we need bash, as that's what bosh invokes for these scripts.[1]
[1] https://github.com/cloudfoundry/bosh/blob/stable-3262.9/bosh_cli/lib/cli/resources/package.rb#L193
`rake build:bosh-cli spec:bosh-cli`
Anyone but @combor or me
=> [#130188061] Add bash to bosh-cli

bosh-init/Dockerfile
[Apply USN-3151-2 everywhere](https://www.pivotaltracker.com/n/projects/1275640/stories/135801295)
As a part of this story, we are going to bump aws cpi version to v62 in this container, to match the version we are using with BOSH, so that the cpi doesn't need to ge compiled every time we re-deploy BOSH.
You can for example create a branch from https://github.com/alphagov/paas-cf/commits/upgrade-stemcell-135801295 and add there a commit that uses this new container. You should then have 0s compile time of the CPI when bosh-init deploys BOSH and concourse. Alternatively, you can trust that all scripting and tests work correctly and only compare the CPI link and sha1 hash in this PR vs [one to be used by bosh](https://github.com/alphagov/paas-cf/commit/06e1c4f37c0d41ff4ea723a6e44909fd48cd489 …
=> [#135801295] BOSH-CLI: bump aws cpi version to v62

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/README.md, cf-acceptance-tests/cf-acceptance-tests_spec.rb
The latest Cloud Foundry upgrade (cf-release v245 to v250) means the
smoke and acceptance tests require golang 1.7+. However, the upstream golang image did not support gzip 1.6, which is used in the new acceptance test code, so we have resorted to using a Dockerfile maintained by CloudFoundry.
**Warning:** merging this will break the tests until the PR: https://github.com/alphagov/paas-cf/pull/735 is not deployed in prod, because we do not pin Docker image versions. 
See notes in https://github.com/alphagov/paas-cf/pull/735 for more details.
You can run the usual local `rake build:cf-acceptance-tests` and `rake spec:cf-acceptance-tests`.
Anyone but me or @keymon
=> [#135948443] Use upstream's image for CATS

terraform/Dockerfile, terraform/terraform_spec.rb
As we refactored terraform config in https://github.com/alphagov/paas-cf/commit/965ae1e977c8298027399e4d09277aa531e7a05a
we started to be hitting https://github.com/hashicorp/terraform/issues/5301 again.
We need to update to a newer terraform version to successfully run terraform in our pipeline.
This needs to be reviewed and merged in conjunction with alphagov/paas-cf#744
Not @alext or @combor
=> [#138486833] Terraform update to v 0.8.5

certstrap/Dockerfile, certstrap/certstrap_spec.rb
Golang 1.5.3 was based on alpine 3.3, which has dropped bash package. Golang
1.7 is based on alpine 3.4 which still has bash. There's currently only rc2
available of golang 1.8. We can bump versions again when we need to.
rake build:certstrap && rake spec:certstrap. Check travis state. You can cherry-pick https://github.com/alphagov/paas-cf/commit/131cb4794195eb861023ff6c1727cae981fb1faa and run your pipelines. Back up (download locally) and then delete certs and let certstrap generate ones. If you don't want to apply, recover old certs from local copy or previous version and upload them again.
not @mtekel
=> Bump cerstrap to golang 1.7

cf-cli/Dockerfile, cf-cli/cf-acceptance-tests_spec.rb
Bump version of cf-cli used in our governmentpaas/cf-cli container to
latest (currently v6.23.1).
Update brings useful features:
- Where available, error messages from 5xx responses from API endpoints now include the request id, which can be helpful for platform operators to look up details on the interaction in CF's internal logs.
- We are in the process of creating a more consistent user experience; our goal is to standardize UI output. For example, warnings and errors will consistently be outputted to stderr instead of stdout. As we iterate through the list of commands, we are also focusing on improving performance and stability.
- This release introduces commands to run, terminate and list tasks, available from CF release v247 
- `delete-space` now takes an optional org parameter to …
=> [#137881471]Update cf cli to v 6.23.1

awscli/README.md, bosh-cli/README.md, cf-cli/README.md, cf-uaac/README.md, curl-ssl/README.md, git-ssh/README.md, json-minify/README.md, psql/README.md, self-update-pipelines/README.md
I noticed this while reviewing #87
We're not very good at maintaining the "Based on XXX image" messages in the
READMEs of each of our containers. I don't think there's much value in
providing this, since the correct information is the in the `Dockerfile` and
people should look there before deciding whether a container is appropriate
for their use.
```
➜  paas-docker-cloudfoundry-tools git:(master) for i in */README.md; do ack Based ${i} && ack FROM $(dirname $i)/Dockerfile; echo; done
Based on [alpine](https://hub.docker.com/_/alpine/) image.
FROM governmentpaas/curl-ssl
Based on the [ruby:slim](https://hub.docker.com/_/ruby/) image.
FROM ruby:2.2-alpine
Based on the [upstream image](https://hub.docker.com/r/relintdockerhubpushbot/cats-concourse-task/), which is
FROM ubuntu:trusty
Based …
```
=> [bugfix] Remove "based on" from READMEs

cf-cli/Dockerfile, cf-cli/cf-acceptance-tests_spec.rb
We want to use this plugin within our alphagov/paas-cf pipeline. At the
moment it will only be for the healthcheck app, which we never want to have
any downtime because we use it for monitoring and automated tests. We may
choose to use it for other apps in the future if this proves successful.
- read the individual commit messages for more information about the changes
- test it with the changes in alphagov/paas-cf#779
Not @dcarley
=> [#121934253] cf-cli: Add blue-green-deploy plugin

spruce/Dockerfile, spruce/spruce_spec.rb
Could you please consider upgrading spruce to recent version. We use this feature https://github.com/geofffranks/spruce/issues/175, introduced in [1.8.2](https://github.com/geofffranks/spruce/releases/tag/v1.8.2)
Thanks
=> bump spruce to version 1.8.9

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
[#139179971 Upgrade CF to >= v252](https://www.pivotaltracker.com/story/show/139179971)
What?
-----
While upgrading to CF v253, the acceptance tests use the command `cf run-task`[1] which was included in cf-cli 6.23.0[2]
We decided upgrade to the latest client version 6.25.0
[1] http://cli.cloudfoundry.org/es-ES/cf/run-task.html
[2] https://github.com/cloudfoundry/cli/releases/tag/v6.23.0
[3] https://github.com/cloudfoundry/cli/releases/tag/v6.25.0
How to review?
-------------
Code review shall be enough
Who?
---
Anyone but @keymon or @csaliceti
=> [#139179971] Upgrade cf-cli to 6.25.0 in cf-acceptance-tests

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb, cf-cli/Dockerfile, cf-cli/cf-acceptance-tests_spec.rb
Update both the cf-cli and cf-acceptance tests containers so that we're using a
consistent version throughout our pipeline.
cf-cli 6.26 include the fix for the 2GB ssh issue.
Review as part of alphagov/paas-cf#900. 
🚨  Do not merge this, until alphagov/paas-cf#900 has been merged and deployed to production
=> [#142400337] Upgrade cf-cli to 6.26 in cf-cli and cf-acceptance-tests containers.

bosh-init/Dockerfile, bosh-init/bosh-init_spec.rb
Story: [Upgrade to BOSH >= 261.3](https://www.pivotaltracker.com/story/show/132565531)
Due to a bug in bosh-init and more recent versions of stemcell we have to update to the version 0.0.100+.
* Build and test locally
* Test with temp commit on the relevant paas-bootstrap PR
* The bootstrap pipeline should be able to build BOSH
* Finalise TEMP commit in paas-bootstrap PR and replace the branch reference with the merge commit SHA
Not @combor or me
=> WIP [#132565531] Update bosh-init to v0.0.100

spruce/Dockerfile, spruce/spruce_spec.rb
This PR updates the version of spruce to the latest version. This
enables `(( static_IPS ))` `(( vault ))` `--go-patch`, `--no-eval`
`spruce diff` options.
It also keeps up up to date with upstream.
Code review
Build locally
Not @LeePorte
=> Update spruce to 1.12.1

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
This commit updates both the go version and the CF CLI version used in
the acceptance tests container.
Tests for v275 are currently failing with
```
Failure [0.196 seconds]
[BeforeSuite] BeforeSuite 
/go/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_test.go:98
CLI version 6.30.0 is required
```
Code check
Build and run tests locally
Not @LeePorte
=> [#151039849] Update go version and CF CLI for acceptance tests

awscli/Dockerfile, awscli/awscli_spec.rb
We'd like to use some functionality (`start-db-instance` and
`stop-db-instance`) in our pipeline. The current version does not cover
these.
We're upgrading to the latest available version on pip as frankly, we
don't see any reason not to.
- Build locally
- Test locally
=> [#150926071] Upgrade AWS CLI tool to the latest version

cf-cli/Dockerfile, cf-cli/README.md, cf-cli/cf-acceptance-tests_spec.rb
We are updating the product page deployment to deploy with a host of `www.cloud.service.gov.uk` (see https://github.com/alphagov/paas-product-page/pull/44.) For this we need the [autopilot](https://github.com/contraband/autopilot) `cf` plugin to be available in `cf-cli` Docker image [being used](https://github.com/alphagov/paas-release-ci/blob/master/pipelines/deploy-app.yml#L91-L98).
Code review
Not @46bit @camelpunch
=> [#153091168] Add autopilot plugin to cf-cli docker image

awscli/Dockerfile, awscli/awscli_spec.rb
jq is a useful additon as the AWS cli often returns with a JSON response which
is easier to parse using jq (especially when we need multiple properties from
the same response).
This PR is needed for https://github.com/alphagov/paas-bootstrap/pull/107.
1. Build the Docker image
```
cd awscli
docker build -t awscli .
cd ..
rspec awscli/awscli_spec.rb
```
Not @bandesz
=> [#153366899] Install jq in the awscli Docker image

awscli/Dockerfile, awscli/awscli_spec.rb
We are using an old version and we need the latest features.
This PR is needed for https://github.com/alphagov/paas-bootstrap/pull/107.
1. Build the Docker image
```
cd awscli
docker build -t awscli .
cd ..
rspec awscli/awscli_spec.rb
```
Not @bandesz
=> [#153366899] Upgrade AWS cli to 1.14.10

bosh-shell/Dockerfile, bosh-shell/bosh-ssh, bosh-shell/bosh_wrapper.rc, bosh-shell/bosh_wrapper.sh, bosh-shell/startup.sh
So that you don't have to run these commands yourself each time you use
`make bosh-cli` from paas-bootstrap, which I find very frustrating. The old
target in paas-cf used to do an equivalent of this for you.
This requires a new environment variable to be passed from paas-bootstrap.
I've called it something other than `DEPLOY_ENV` to make it easier to
understand what it is used for.
Rather than requiring people to run a separate command because I keep
forgetting this. This works because `exec bosh` within the script doesn't
use the `alias` set in the shell.
The existing `bosh --version` spec test should make sure that normal bosh
usage still works. I don't think we can do much more without a director.
See alphagov/paas-bootstrap#118
Anyone, but possibly @alext while on support.
=> bosh-shell improvements

spruce/Dockerfile, spruce/spruce_spec.rb
Using the latest spruce version, doesn't require usage of ! to escape  BOSH/Concourse
variables.
=> bump spruce to 1.14 and alpine to 3.7

psql/Dockerfile, psql/psql_spec.rb
Newer versions of Alpine (>=3.4) support search domains in `resolv.conf`. Without this it is tricky to run this image within k8s.
This fixes tests from PR #110.
=> Upgrade psql Docker image to latest Alpine version

bosh-init/Dockerfile
[#154437339 Upgrade BOSH director and AWS CPI](https://www.pivotaltracker.com/story/show/154437339)
What?
-----
We want to upgrade our bosh-aws-cpi to use the latest version v69.[1][2]
We update the governmentpaas/bosh-init container to include the
cache of this new version, so bosh-init won't need to build and
compile it every time.
How to review?
--------------
* Code review
* `rake build:bosh-init spec:bosh-init `
Who?
---
Anyone but @keymon or @henryk
[1] https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/releases/tag/v69
[2] https://bosh.io/releases/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?version=69
=> [#154437339] Update bosh-init to cache bosh-aws-cpi v69

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
Upgrade cf-cli to latest.
Using cloudfoundry/cf-acceptance-tests@cf1.14 for
cloudfoundry/cf-deployment@v1.14.0 has this failure with the previous
version of the container:
CLI version 6.33.1 is required
Expected
<bool>: false
to be true
See alphagov/paas-cf#1229
Anyone.
=> [#154769249] cf-acceptance-tests: Upgrade cf-cli

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
https://www.pivotaltracker.com/n/projects/1275640/stories/156299675
What?
-----
The cf-acceptance-tests used by alphagov/paas-cf#1306 uses
a new command: `cf add-network-policy`, that was added in
cf 6.35.0, so the tests fail.
We upgrade to the latest cf-cli version.
How to review
------------
Review with alphagov/paas-cf#1306
who?
----
=> [#156299675] Use cf-cli 6.36.0 for CATs tests

bosh-shell/README.md, bosh/Dockerfile, bosh/README.md, bosh/bosh_spec.rb, bosh/hooks/README.md, bosh/hooks/post_push, bosh/startup.sh
This allows you to execute one-off commands using Bosh. The initial
motivation for this comes from the repository paas-infrastructure-map,
which provides the tools necessary to query Bosh and build a dynamic
map of a Bosh deployment.
We use the empty exec-style `CMD` declaration to override the command
of the base Ruby image.
=> [Firebreak] Add image for executing arbitrary Bosh commands

cf-cli/Dockerfile, cf-cli/cf-acceptance-tests_spec.rb
What?
----
I want to generate the manifest of the product page, pulling  secrets from .yml files in S3 buckets as we still don't have any sensible proper solution for this.
spruce[1] is a nice tool to kickly generate manifests, pull secrets from other variables, etc. It is handy to have it in the cf-cli container to simplify our pipelines, so that we can build a manifest and add the required config (env vars, secrets, routes, etc) seamlessly.
We also want to add bash, as it has more capabilities than the simple `sh`, we can write simpler scripts. The additional consume sized is minimal.
[1] https://github.com/geofffranks/spruce
How to review?
--------------
Code review
Who?
---
Anyone but me
=> [#155037639] Add spruce to cf-cli for manifest templating

LICENCE.md
We had an [issue raised](https://github.com/alphagov/paas-docker-cloudfoundry-tools/issues/127) regarding the license type we used. This PR clarifies this.
Confirm that the added license conforms to the [GDS way](https://gds-way.cloudapps.digital/manuals/licensing.html#each-repository-should-include-a-licence-file)
Not @LeePorte
=> Add the MIT licence to the repo

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
https://www.pivotaltracker.com/story/show/157083954
What?
-----
We want to test the log-cache service using the cf-acceptance-tests[1], but
for that we need the corresponding plugin installed in the container.
Additionally, as the tests would change the CF_HOME variable, we must
set the CF_PLUGIN_HOME at the container level so the containers
are available when the tests run.
How to review?
------
Review as part of https://github.com/alphagov/paas-cf/pull/1371
Dependencies
----------
Update https://github.com/alphagov/paas-cf/pull/1371 once this is merged
and the new container generated
Who?
----
Anyone but me or @paroxp
[1] https://github.com/cloudfoundry/cf-acceptance-tests/commit/923a0fe9335bf0a1e75286801e952f248491cd38
=> [#157083954] Add the log-cache plugin to the cf-acceptance-tests container

bosh-shell/Dockerfile, bosh-shell/bosh-shell_spec.rb, bosh/Dockerfile, bosh/bosh_spec.rb
What?
----
We have update the bosh-cli-v2 to use bosh-cli 5.2.1 with SKI for
certs, and we want to use the same in the rest of containers
for consistency.
The version 5.2.1 [1] supports generating certificates via
--vars-store with SKI/AKI.
We need this to be able to rotate CA certificates used by CF API,
otherwise it is not possible to use two CA certs with the same name
at the same time.
More info in [2]
[1] https://github.com/cloudfoundry/bosh-cli/releases/tag/v5.2.1
[2] https://github.com/cloudfoundry/config-server/pull/9
How to review?
-----
code review, tests pass
Who?
----
not me
=> [#160614327] Update bosh-cli for bosh and bosh-shell

bosh-shell/startup.sh
Bosh is becoming more dependent on using UAA to authenticate, so we are
going to start using UAA. This means on every operation you have to pass
these flags, otherwise it can use the wrong OAuth flow. For example, the
initial `bosh login` may work, but a subsequent `bosh vms` operation
will result in authorization failure.
The correct usage of the Bosh CLI now is to use the environment
variables `BOSH_CLIENT` and `BOSH_CLIENT_SECRET`, which ensures the
correct authentication flow on every operation. We can pass said
variables when invoking this image, so don't need to reference them in
this script.
Review with the pull request on paas-bootstrap
Anyone but me or @keymon
=> [#161388997] Don't pass command line parameters to `bosh login`

bosh-shell/startup.sh
Now we are passing the environment variables `BOSH_CLIENT` and
`BOSH_CLIENT_SECRET` we do not need to perform a login. The Bosh CLI
will negotiate authentication on every operation anyway. Removing this
has the added benefit of not failing the startup script if login fails,
which means you can inspect the contents of the container more easily.
This will be merged by me or @keymon as part of https://github.com/alphagov/paas-bootstrap/pull/204
=> [#161388997] No longer do `bosh login` in bosh-shell entrypoint

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
What?
----
During the upgrade of cf-deployment to v6.0.0[1] log-cache has been
upgraded. The new version of log-cache uses a new protocol
and it is not compatible with old clients.
We need to update the log-cache cf client plugin that runs on the
tests.
[1] https://github.com/cloudfoundry/cf-deployment/releases/tag/v6.0.0
How to review
-----------
Code review. Travis should pass
Who?
----
Not me
=> [#161544435] Upgrade cf-log-cache plugin and cf-cli

bosh-cli-v2/Dockerfile, bosh-cli-v2/bosh_init_cache/minimal_in.yml
What?
----
In the container bosh-cli-v2 we precompile the bosh-cpi release
to speed up the deployments.
In this commit we update the version of the bosh-cpi and the
related stemcell to put it in sync with the new version in
paas-bootstrap[1]
[1]  https://github.com/alphagov/paas-bootstrap/pull/210
How to review
------------
Code review.
Merge, build the container and adapt references in paas-bootstrap and
paas-cf pipeline
Who?
---
Not me
=> [#161544435] Update bosh cpi and base stemcell

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
What
----
This PR adds the AWS CLI to the cf acceptance tests docker image in
order for us to be able to replicate current smoke test failure sending
an alert email for each test fail, and firing a pagerduty alert on 3
consecutive failures.
How to review
----
code review and tests passing
Who can review?
----
Not @leePorte
=> Added AWS-CLI to cf-acceptance tests container.

bosh-cli-v2/Dockerfile
What?
----
Follow up of https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/140
v73 is too new, it has not release notes, and it seems to be
a major refactoring to introduce v2 api[1][2]
One team member had some issues with it already.
We downgrade to v72 to be on the safe side.
[1] https://github.com/cloudfoundry/bosh-aws-cpi-release/releases/tag/v73
[2] https://github.com/cloudfoundry/bosh-aws-cpi-release/compare/v72...v73
How to review
------------
code review, test should pass
Who?
----
Not me
=> [#161544435] Downgrade bosh-cli-v2 bundled bosh-cpi to v72

terraform/plugin_cache.tf
The current version doesn't support the new ACM resources[1] which we need to manage our ACM certs using Terraform instead of the existing scripts.
[1]https://www.terraform.io/docs/providers/aws/r/acm_certificate_validation.html
Review along with https://github.com/alphagov/paas-cf/pull/1646 and https://github.com/alphagov/paas-bootstrap/pull/220
Not me.
=> [#161184357] Upgrade AWS terraform provider to 1.46.0

curl-ssl/Dockerfile, curl-ssl/curl-ssl_spec.rb
Exactly the same explanation as in #137, but for curl-ssl.
This is specifically needed to simplify the deployment of new grafana dashboards
=> Include `gettext` in curl-ssl image

git-ssh/Dockerfile, git-ssh/git-ssh_spec.rb
Closes #155
What
---
Our `git-ssh/README.md` says `curl` and `openssl` are installed. They were not, now:
- Adds tests for curl and openssl
- Has them installed
How to review
---
Code review
=> Fix git-ssh image

cf-cli/Dockerfile, cf-cli/cf-cli_spec.rb
What
---
- Update CF CLI 6.45 in cf-cli docker image
- Remove old FIXME for alpine 3.6
Why
---
So we can run the latest CATS
How to review
---
Code review
Travis
=> Bump CF CLI to v6.45

cf-cli/Dockerfile, cf-cli/cf-cli_spec.rb
`Envsubst` implements *just* enough of a basic templating system to
allow CF manifests to use envvars easily. This allows inline/pipeline
verbosity such as this:
```bash
$ ruby -ryaml -e "
env = {
'LOG_CACHE_API' => 'https://log-cache.${SYSTEM_DNS_ZONE_NAME}',
}
manifest = YAML.load_file('manifest.yml')
manifest['applications'].each { |app|
app['env'] = {} unless app['env']
app['env'].merge!(env)
app['routes'] = [
{ 'route' => 'metrics.${SYSTEM_DNS_ZONE_NAME}' }
]
}
File.write('manifest.yml', manifest.to_yaml)
"
$ cf zero-downtime-push paas-log-cache-adapter -f manifest.yml
```
... to be replaced with this:
```bash
$ cf zero-downtime-push paas-log-cache-adapter -f <(envsubst '$SYSTEM_DNS_ZONE_NAME' <manifest.yml)
```
Adding this package doesn't mandate its use, of course; it merely …
=> Include gettext's `envsubst` in the cf-cli image

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
We need to update the CF CLI version due to changes in commands in CF 9.x series. I have updated the tests and also changed the base container to a Xenial container.
=> Update CF CLI version

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
The acceptance tests are now using go modules. As a result we need a suitable version of go in the container.
=> Upgrade go to latest version for acceptance tests

bosh-cli-v2/Dockerfile
[Story](https://www.pivotaltracker.com/story/show/166728064)
What
---
In order to use NVMe based instance types (t3, m5, r5, c5) we need to
use CPI version >=v74
This commit upgrades the version of the bosh-aws-cpi-release to v75 which can use NVMe based instances
=> [#166728064] Upgrade bosh-aws-cpi to v75

bosh-shell/Dockerfile, bosh-shell/startup.sh
What
---
Now that we configure credhub CLI as part of this container, we have reasonable
call to use it to access secrets in a non-interactive fashion as part of our
dev tooling. This PR feeds the command used to run the container through to the
bash shell started in `startup.sh`.
In order to correctly run a command, scripts should prefix their commands with
`-c`, as if they were running `bash -c 'command'" (which they are). E.g.
```
docker run \
--rm \
governmentpaas/bosh-shell:latest \
"-c 'credhub --version'"
```
Interactive usage should continue to function as normal when the container is
run interactively without a command. E.g.
```
docker run -it --rm governmentpaas/bosh-shell:latest
```
How to review
---
1. Code review
2. Build it locally and make a couple test scripts for the …
=> [#167971884] Allow non-interactive bosh-shell usage

terraform/Dockerfile, terraform/plugin_cache.tf, terraform/terraform_spec.rb
What
----
Updates terraform to 0.11.14 and terraform-provider-aws to 2.30.0
We experience crashes when creating (and sometimes deleting) using our very old version of terraform 0.11.1 and terraform-provider-aws 1.46
Bump the images
Once the images are built we can test the later versions in pipelines to see if things are tangibly better
How to review
---
```
git fetch
git checkout -b terraform0.11.14 origin/!#:3
rake build:terraform
rake test:terraform
```
=> Update terraform to 0.11.14 and terraform-provider-aws to 2.30.0

curl-ssl/Dockerfile, curl-ssl/curl-ssl_spec.rb
It would be really useful to have `jq` available in the `curl-ssl` image, so json responses can be parsed easily.
This change adds that tool.
=> [Firebreak] Add jq to curl-ssl image

.travis.yml, cf-cli/Dockerfile, cf-cli/cf-cli_spec.rb
- Notify in particular need make along with the cf-cli for doing
deployments on Concourse
- Add a package and test for that package to include make in the image
=> Add make to cf-cli image

cf-cli/Dockerfile, cf-cli/cf-cli_spec.rb
Bump version of cf-cli used in governmentpaas/cf-cli container to
latest (currently v6.46.1, v7.x still in beta)
=> Update cf cli to v 6.46.1

bosh-shell/startup.sh
What
---
We're switching to use individual accounts instead of shared creds. This updates the bosh-shell image with a USER_ID_RSA var so we can pass in user specific keys.
How to review
---
- Code review
- Build locally and update image used [here](https://github.com/alphagov/paas-bootstrap/compare/indiviual-accounts-166500017?expand=1#diff-1f5c6bd196a437e4dca5a2c70344b48cL50)
Who can review
---
Not me
=> [#166500017] Add option to pass in a user's key

cf-cli/Dockerfile, cf-cli/cf-cli_spec.rb
Bump version of cf-cli used in governmentpaas/cf-cli container to
latest (currently v6.47.2, v7.x still in beta)
=> Update cf cli to v 6.47.2

awscli/Dockerfile, awscli/awscli_spec.rb, self-update-pipelines/Dockerfile, self-update-pipelines/self-update-pipelines_spec.rb
My selfish reason for wanting this is to get support for the [k8s IAM
magical auth support][1] but it's probably good to keep updating this
for all sorts of reasons.
1.17.0 dropped support for python 2.6 and 3.3; I don't think that's a
concern for us here?
[1]: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html
=> bump to latest awscli version

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
when we use go mod, it can get dependencies using many version control systems
it needs bzr and git installed, just add em all
=> cf-acceptance-tests: use go 1.14 and have all vcs

awscli/Dockerfile
Per https://github.com/boto/boto3/issues/2596#issuecomment-694508466
The PaaS might not use this but we've seen it when re-using the image for
OctoDNS and trying to `pip3 install boto3` on top of governmentpaas/awscli.
=> Bump awscli version

bosh-cli-v2/Dockerfile, bosh-cli-v2/bosh-cli_spec.rb
Hi There!
A PR to bump to latest cli available (bosh and credhub)
=> bosh-cli-v2: update to 6.4.1; credhub to 2.8.0

spruce/Dockerfile, spruce/spruce_spec.rb
Spruce bump is required to be consistent with embedded spruce in cf-cli image.
This is related to  #203
=> spruce: bump to v1.27.0

alpine/Dockerfile, alpine/README.md, concourse-pool-resource/Dockerfile, concourse-pool-resource/README.md, golang/Dockerfile, node/Dockerfile, olhtbr-metadata-resource/Dockerfile, ruby/Dockerfile, ruby/README.md
DockerHub recently started rate limiting. As a result we are stopping using DockerHub for high-volume production CI/CD pipelines. This commit finishes off that work.
This commit creates 3 new Dockerfiles corresponding to the 3 remaining uses of DockerHub in our pipelines. We want to use GitHub Container Registry, but these external images aren't available there yet.
Alternative is to have something copy these 3 upstream images across to GitHub Container Registry, but that doesn't fit with the existing pattern we have in this repo.
See if things go green, and decide if you're OK with this approach.
Once this is merged there's then https://github.com/alphagov/paas-release-ci/pull/162 to review, which builds these images and pushes them to GCHR.
=> [#176226306] Build mirrored DockerHub images for us to use in production

bosh-cli-v2/Dockerfile, bosh-cli-v2/bosh-cli_spec.rb
Latest available versions:
bosh-cli: 6.4.4
bosh-aws-cpi: 87
credhub-cli: 2.9.0
Our bosh stemcell upgrade is blocked by bosh-cli < 6.4.4
=> Bump bosh-cli, bosh-aws-cpi, credhub-cli versions

bosh-cli-v2/Dockerfile
This will be useful for the resurrector-monitoring job.
=> [#178621826] bosh-cli-v2: add `jq`

bosh-cli-v2/Dockerfile, bosh-cli-v2/bosh-cli_spec.rb
Can already hear the question "doesn't this make `jq` unnecessary?", answer "no, `yq` is much less powerful than `jq`".
This is so that we can do some very basic value extraction on manifests fetched from bosh in the pipeline.
=> [#178621826] bosh-cli-v2: add yq

node-chromium/Dockerfile
Essentially we need a headless browser to be performing some of our acceptance tests in.
=> Add node-chromium image

.github/workflows/build-image-base.yml
Our existing images use 'ghcr.io/alphagov/paas/${NAME}'. It seems like this is a gds standard, so let's use that instead.
=> Fix image naming

.github/workflows/build-image-base.yml
I'm so bad at github. we do need 'alphagov' in there.
=> amend image name, to keep consistent with existing images

.github/workflows/alpine.yml, .github/workflows/awscli.yml, .github/workflows/bosh-cli-v2.yml, .github/workflows/build-image-base.yml, .github/workflows/certstrap.yml, .github/workflows/cf-acceptance-tests.yml, .github/workflows/cf-acceptance-tests_ginkgo2.yml, .github/workflows/cf-cli.yml, .github/workflows/cf-uaac.yml, .github/workflows/concourse-pool-resource.yml, .github/workflows/curl-ssl.yml, .github/workflows/git-ssh.yml, .github/workflows/golang.yml, .github/workflows/json-minify.yml, .github/workflows/middleman.yml, .github/workflows/node-chromium.yml, .github/workflows/node.yml, .github/workflows/olhtbr-metadata-resource.yml, .github/workflows/paas-prometheus-exporter.yml, .github/workflows/psql.yml, .github/workflows/ruby.yml, .github/workflows/self-update-pipelines.yml, .github/workflows/spruce.yml, .github/workflows/terraform.yml, Makefile
As we're no longer pushing to a repo-scoped image, the automatically
provided GITHUB_TOKEN is no longer useful for pushing.
Instead, use the existing CI_USER_* secrets from paas-pass.
If these need to be re-uploaded (ie. after rotation), this can be done
via the make task 'upload-ghcr-secrets'
=> Use the CI user secrets

.github/workflows/alpine.yml, .github/workflows/awscli.yml, .github/workflows/bosh-cli-v2.yml, .github/workflows/build-image-base.yml, .github/workflows/certstrap.yml, .github/workflows/cf-acceptance-tests.yml, .github/workflows/cf-acceptance-tests_ginkgo2.yml, .github/workflows/cf-cli.yml, .github/workflows/cf-uaac.yml, .github/workflows/concourse-pool-resource.yml, .github/workflows/curl-ssl.yml, .github/workflows/git-ssh.yml, .github/workflows/golang.yml, .github/workflows/json-minify.yml, .github/workflows/middleman.yml, .github/workflows/node-chromium.yml, .github/workflows/node.yml, .github/workflows/olhtbr-metadata-resource.yml, .github/workflows/paas-prometheus-exporter.yml, .github/workflows/psql.yml, .github/workflows/ruby.yml, .github/workflows/self-update-pipelines.yml, .github/workflows/spruce.yml, .github/workflows/terraform.yml
Github actions is a bit arcane in some ways.
By default, secrets aren't passed directly to reusable workflows,
because otherwise you could end up passing secrets to a bad actor
if using a workflow from a third party.
Normally, we would have to specify the specific secrets that need to be
passed to the reusable workflow, but as it's a local one, we can just
specify that it inherits the provided secrets.
Note: I'm not sure why the GITHUB_TOKEN automatic secret doesn't cause
these same issues!
=> Allow passing secrets to the reusable workflow

curl-ssl/Dockerfile
Build curl-ssl with our alpine image as a base.
This takes pressure off of #233, as it depends on a image that that PR is introducing
Describe the steps required to test the changes.
* Merge #233
* Rebase against `main`, force push and check the pipelines run
* Move on to #236
=> [#182295946] Build curl-ssl using our alpine base image

alpine/Dockerfile
Description:
- Older OpenSSL image isn't present in the Alpine repository so we have to bump up to ensure the GitHub actions pass
=> 182427769 - Upgrade OpenSSL alpine base image

ubuntu/Dockerfile
export `DEBIAN_FRONTEND=noninteractive` in the base image, so that apt behaves as expected in child images
- Sense check
=> set apt to be noninteractive

cf-acceptance-tests/Dockerfile
Description:
- Since app-autoscaler is upgraded to 8.0.0 (see https://github.com/alphagov/paas-cf/pull/2994) the tests need Go 1.19 to run
Describe what you have changed and why.
See latest build on dev02 using pr-251 for cf-acceptance-tests.
=> 182889631 Upgrade brokered autoscaler to V8

bosh-cli-v2/Dockerfile, bosh-cli-v2/bosh-cli-v2_spec.rb, cf-cli/cf-cli_spec.rb, ruby-base/Dockerfile, ruby/Dockerfile, self-update-pipelines/Dockerfile, self-update-pipelines/self-update-pipelines_spec.rb
Wherever we use Ruby in a Docker image, upgrades to Ruby 3.1
Check the images are built successfully, and tests pass.
N.B. because some images (such as `cf-cli`) reference `ghcr.io/alphagov/paas/ruby-base:main`, they won't _actually_ get Ruby 3.1 until this PR is merged
=> Use Ruby 3.1 across the board

kipper/Dockerfile
bumped the awscli version to 1.27.90 (latest as of now) because the previous version doesn't include the taglist metatdata in describe-db-instances that I need for kipper  
look at the code
=> updated awscli version to get taglist metadata for kipper

awscli/Dockerfile, awscli/awscli_spec.rb, bosh-cli-v2/Dockerfile, certstrap/Dockerfile, cf-acceptance-tests/Dockerfile, cf-cli/Dockerfile, cf-uaac/Dockerfile, curl-ssl/Dockerfile, fast-startup-and-shutdown/Dockerfile, git-ssh/Dockerfile, golang/Dockerfile, paas-prometheus-exporter/Dockerfile, self-update-pipelines/Dockerfile, self-update-pipelines/self-update-pipelines_spec.rb, spruce/Dockerfile
Descriptions:
- See commit for dependencies that are upgraded
- See [here](https://deployer.dev03.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/pipeline-lock/builds/24) for a clean run in our dev environment
=> 18504128 - Upgrade CLI versions in paas-docker-cloudfoundry-tools

.github/dependabot.yml, .github/workflows/build-image-base.yml, .github/workflows/lint_on_pr.yml
Description:
- Currently we pin to versions which means that we automatically pull in the latest changes which presents a security risk as we don't know which code is running in our build pipeline.
- This PR fixes this by pinning to a specific hash
Verify that GitHub actions successfully run
=> 185509385 - Pin GitHub Actions to specific hashes

terraform/Dockerfile, terraform/terraform_spec.rb
https://www.pivotaltracker.com/story/show/185500753
See the most recent bringup of `dev02`, which was done with this image?
=> terraform: 1.3.3 -> 1.5.2

bosh-cli-v2/Dockerfile, bosh-cli-v2/bosh-cli-v2_spec.rb, bosh-cli-v2/bosh_init_cache/seed_bosh_init_cache.sh
Version updates to bosh-cli-v2 container:
- bump bosh cli version to 7.3.1
- bump bosh aws cpi to version 99
- bump credhub cli version to 2.9.19
- bump yq version to 4.35.1
Clean up packages folder at the end of the bosh create-env.
If we don't clean the packages and we have a different cpi version built upstream we can get "idempotent" issues.
For example:
```
mkdir: cannot create directory '/root/.bosh/installations/44f01911-a47a-4a24-6ca3-a3109b33f058/packages/aws-cpi-ruby-3.1/bosh': File exists
```
[Example build failure](https://deployer.dev04.dev.cloudpipeline.digital/teams/main/pipelines/create-bosh-concourse/jobs/bosh-deploy/builds/30#L64ab2e1b:2092)
Look at the changes.
These changes have been test against dev-04. Both paas-bootstrap and paas-cf.
=> Updates to bosh-cli-v2

awscli/Dockerfile
- paas-bootstrap's create-bosh-concourse [pipeline](https://github.com/alphagov/paas-bootstrap/blob/9061827f4c35ac844d1e4dfdefb2eb3e167cf13f/concourse/pipelines/create-bosh-concourse.yml#L645) installs openssh using apk but it should be bundled as part of the docker image
- Bundle openssh into the awscli docker image
- See [https://deployer.dev02.dev.cloudpipeline.digital/teams/main/pipelines/create-bosh-concourse/jobs/update-pipeline/builds/15](https://deployer.dev02.dev.cloudpipeline.digital/teams/main/pipelines/create-bosh-concourse/jobs/update-pipeline/builds/15) for a clean run of `create-bosh-concourse`
- See [https://deployer.dev02.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/pipeline-lock/builds/70](https://deployer.dev02.dev.cloudpipeline.digital/teams/m …
=> 186049138 - Update awscli image to include openssh

awscli/Dockerfile
- There is no need for the server packages as in paas-bootstrap we only use it to generate ssh-keys
- See successful run at https://deployer.dev02.dev.cloudpipeline.digital/teams/main/pipelines/create-bosh-concourse/jobs/test-aws-cli-image/builds/2
- See successful run at https://deployer.dev02.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/pipeline-lock/builds/72
- See successful run at https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/setup/jobs/self-update/builds/108
=> 186049138 - awscli docker image uses openssh-client rather than openssh

ubuntu/Dockerfile
we need to update these refs to the old bionic ubuntu versions as the apt repos seem to have been removed, which is preventing the pipelines running on the billing integration tests...
Look at the code
=> updating ubuntu bionic->jammy

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
We are trying to eliminate any apt-get install remnants in our pipelines by loading requirements in the docker images.
This PR will include postgresql and postgresql-client needed in acceptance-tests.
Verify that the image contains postgresql and postgresql-client installed.
=> [186049138] Postgresql is used in acceptance tests

bosh-cli-v2/Dockerfile
bumped aws cpi 99->101 to support new instance generation disk layouts
look at the code, and/or the deploy in dev04
=> bumped aws cpi 99->101

.github/workflows/build-image-base.yml, bosh-cli-v2/Dockerfile, cf-uaac/Dockerfile, cf-uaac/cf-uaac_spec.rb, middleman/Dockerfile, ruby/Dockerfile
Fixes:
* Fixed the bosh CLI download URL, these are now hosted on github releases and the old S3 bucket doesn't have the releases anymore
* Update the UAAC version, the old version fails to launch
* Bump the setup ruby github action version
* Install concurrent-ruby before middleman as a workaround for https://github.com/middleman/middleman/issues/2788
* Update ruby version to 3.4. Use the docker hub image directly in middleman for now
We should change the middleman base image back to paas-ruby after merging this, it currently uses the latest tagged version (3.1) but middleman needs ruby >= 3.2 to work. Underlying issue is https://github.com/middleman/middleman/issues/2788
=> Fix GitHub actions CI

cf-acceptance-tests/Dockerfile, cf-acceptance-tests/cf-acceptance-tests_spec.rb
* Update go to latest available, 1.24.0
* Update CF CLI to 8.10.0
* Update CF log cache CLI plugin to 6.2.1
=> Update tools used in cf-acceptance-tests image
